### ISSUE TITLE
建议使用doPassiveScan

### ISSUE THREAD

**Issue by No4l** [gh0stkey/CaA#1]
因为用了云数据库，所以出了点儿问题Orz。`processHttpMessage`每次处理请求的时候要🔗数据库，就导致处理时间变长，然后响应时间就变慢了，略微影响了使用😭，这种情况下是不是`doPassiveScan`兼容性要高点儿👀

**Comment by gh0stkey** [comment]
你好，感谢建议，考虑到可能会有“联机”或云数据库这种需求，`processHttpMessage`确实不是最佳选择，目前正在修改相关代码，发布下一个版本。

**Comment by gh0stkey** [comment]
0.2版本已经更新，感谢：https://github.com/gh0stkey/CaA/releases/tag/0.2
