### ISSUE TITLE
安装插件出现报错

### ISSUE THREAD

**Issue by robot183** [gh0stkey/CaA#10]
![image](https://github.com/gh0stkey/CaA/assets/55733256/968c2cb9-fd48-4259-9b03-1efcd7a8e9f1)

是需要单独配置数据库么

**Comment by robot183** [comment]
还是burp,jdk的版本过低了

**Comment by gh0stkey** [comment]
请检查你的BurpSuite是否是近3个月内发布的，如果不是请更新，谢谢～

**Comment by robot183** [comment]
了解啦，多谢
