### ISSUE TITLE
运行后没有任何数据

### ISSUE THREAD

**Issue by aiilq** [gh0stkey/CaA#18]
## 使用环境

```
CaA版本：Beta 0.9
BurpSuite版本：v2024.4.5
JDK版本：BurpSuite自带
操作系统版本：win10
```

## 问题详情

问题描述：
send to fuzzer后，在taskboard页面只能搜索到task name，下方无数据。
![Uploading 图片3.png…]()

出现的场景：
开始fuzz

## 解决建议

无。

**Comment by gh0stkey** [comment]
目前CaA正在进行1.0正式版的重构当中，敬请等待。

**Comment by aiilq** [comment]
> 目前CaA正在进行1.0正式版的重构当中，敬请等待。

感谢回复，期待
