### ISSUE TITLE
【功能优化】师傅，路径功能能否优化为完整路径

### ISSUE THREAD

**Issue by Wwon1oung** [gh0stkey/CaA#19]
## 使用环境

```
CaA版本：0.9
BurpSuite版本：
JDK版本：BurpSuite自带
操作系统版本：
```

## 问题详情

问题描述：
师傅，路径功能能否优化为完整路径，提取到的路径都是单级路径/cc这样，能否优化为完整路径/aa/bb/cc这样
<img width="257" alt="image" src="https://github.com/gh0stkey/CaA/assets/55070231/0065b771-15ba-4ca6-9132-5fb2790d140a">

出现的场景：

## 解决建议

无。

**Comment by gh0stkey** [comment]
目前CaA正在进行1.0正式版的重构当中，敬请等待。

**Comment by gh0stkey** [comment]
新版本已添加完整路径`FullPath`
