### ISSUE TITLE
查询结果能否支持csv导出功能

### ISSUE THREAD

**Issue by moyuwa** [gh0stkey/CaA#2]
你好，非常感谢你编写这款实用的工具，我有个建议，能不能支持查询结果导出，能导出txt、csv之类的简单格式就行，还有查询时能否支持主域名，比如“sp2.baidu.com”只需要输入“baidu.com”即可查到。

**Comment by gh0stkey** [comment]
你好，感谢你诚恳的建议，关于这两个功能，我们会酌情考虑，如果采纳，预计会在下个版本发布。
