### ISSUE TITLE
该插件是否支持低版本java

### ISSUE THREAD

**Issue by shuaxingzi** [gh0stkey/CaA#4]
师傅您好，该插件是否支持低版本java，java版本java8
![image](https://user-images.githubusercontent.com/44746140/163330261-04e4275d-ad90-4158-8139-271a361dceb9.png)

**Comment by gh0stkey** [comment]
最新的releases加了jdk8编译的jar包，可以看看。

**Comment by shuaxingzi** [comment]
> 

已解决，感谢师傅
