### ISSUE TITLE
遇到收集不到的目录

### ISSUE THREAD

**Issue by DatangST** [gh0stkey/CaA#5]
![image](https://user-images.githubusercontent.com/52750566/208709123-2dedcdb6-f420-4322-b938-6e4058469fd8.png)
这种#号的似乎压根不会加载到burp

**Comment by gh0stkey** [comment]
你可以抓包看一下你是否能抓到这个请求，很显然是不行的。这里的URL并不是一个完整的URL，`#/login`是锚点，是一个前端页面的定位器，根本不会带入到请求中，自然也就不可能被收集到。

**Comment by DatangST** [comment]
在正常情况的URL中，我BURP在不断的使用。数据库中查看也没抓取到相应的数据

这种锚点的东西似乎爆破目录也不行，抓取也不行。遇到很多类似的只能一个个去测试。但是我用正常站点，burp也连接成功也一直没抓取到数据库中






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月23日(星期五) 下午5:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gh0stkey/CaA] 遇到收集不到的目录 (Issue #5)





 
你可以抓包看一下你是否能抓到这个请求，很显然是不行的。这里的URL并不是一个完整的URL，#/login是锚点，是一个前端页面的定位器，根本不会带入到请求中，自然也就不可能被收集到。
