### ISSUE TITLE
burp导入后数据库也连接成功，挖洞时一直未存入数据库。整个数据库表是空的

### ISSUE THREAD

**Issue by DatangST** [gh0stkey/CaA#6]
burp导入后数据库也连接成功，挖洞时一直未存入数据库。整个数据库表是空的

**Comment by gh0stkey** [comment]
麻烦说明一下Burp的版本

**Comment by gh0stkey** [comment]
你的数据库自己链接过 可以写入数据吗

**Comment by DatangST** [comment]
&nbsp;&nbsp;

&nbsp; 是可以上传的。我一直找师傅微信没找到。找到林晨师傅去了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月6日(星期五) 中午11:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gh0stkey/CaA] burp导入后数据库也连接成功，挖洞时一直未存入数据库。整个数据库表是空的 (Issue #6)





 
你的数据库自己链接过 可以写入数据吗

**Comment by DatangST** [comment]
原谅我没明白师傅的意思




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月11日(星期三) 上午9:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gh0stkey/CaA] burp导入后数据库也连接成功，挖洞时一直未存入数据库。整个数据库表是空的 (Issue #6)





 
Closed #6 as completed.

**Comment by gh0stkey** [comment]
加我微信：EVILCHEN__
