### ISSUE TITLE
v0.5版本连接数据库后成功创建表结构，但无数据

### ISSUE THREAD

**Issue by ThestaRY7** [gh0stkey/CaA#7]
环境：
intel macOS 13.3.1 (22E261)
Burp Suite Professional v2022.12.5
CaA-0.5-J8.jar
MYSQL Server version: 8.0.32 Homebrew

(BP使用的是高版本JDK，但是我在Bp的Extensions-Options-Java Environment配置了JAVA1.8.0_151环境，我其他插件如HaE(2.4.6)、xia SQL V3.3均使用的是J8版本。)

情况：
Connect后无异常报错，数据库成功创建表结构。
<img width="1355" alt="image" src="https://github.com/gh0stkey/CaA/assets/48352738/a97e925b-e834-423d-a2e9-960e376c4e8d">

请问和创建数据库选择的这些有关系吗？
<img width="479" alt="image" src="https://github.com/gh0stkey/CaA/assets/48352738/afa3c945-e72a-4641-9959-114689259d27">

**Comment by gh0stkey** [comment]
我的数据库结构是这样的，没有问题，可以参考下：
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for Endpoint
-- ----------------------------
DROP TABLE IF EXISTS `Endpoint`;
CREATE TABLE `Endpoint` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `host` varchar(300) DEFAULT NULL,
  `value` varchar(300) DEFAULT NULL,
  `count` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=34508 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for Endpoints
-- ----------------------------
DROP TABLE IF EXISTS `Endpoints`;
CREATE TABLE `Endpoints` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `value` varchar(300) DEFAULT NULL,
  `count` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=25611 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for File
-- ----------------------------
DROP TABLE IF EXISTS `File`;
CREATE TABLE `File` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `host` varchar(300) DEFAULT NULL,
  `value` varchar(300) DEFAULT NULL,
  `count` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=68071 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for Files
-- ----------------------------
DROP TABLE IF EXISTS `Files`;
CREATE TABLE `Files` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `value` varchar(300) DEFAULT NULL,
  `count` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=62541 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for FullPath
-- ----------------------------
DROP TABLE IF EXISTS `FullPath`;
CREATE TABLE `FullPath` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `host` varchar(300) DEFAULT NULL,
  `value` varchar(300) DEFAULT NULL,
  `count` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=20004 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for FullPaths
-- ----------------------------
DROP TABLE IF EXISTS `FullPaths`;
CREATE TABLE `FullPaths` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `value` varchar(300) DEFAULT NULL,
  `count` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=16835 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for Param
-- ----------------------------
DROP TABLE IF EXISTS `Param`;
CREATE TABLE `Param` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `host` varchar(300) DEFAULT NULL,
  `value` varchar(300) DEFAULT NULL,
  `count` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=410877 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for Params
-- ----------------------------
DROP TABLE IF EXISTS `Params`;
CREATE TABLE `Params` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `value` varchar(300) DEFAULT NULL,
  `count` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=320428 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for Path
-- ----------------------------
DROP TABLE IF EXISTS `Path`;
CREATE TABLE `Path` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `host` varchar(300) DEFAULT NULL,
  `value` varchar(300) DEFAULT NULL,
  `count` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4817 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for Paths
-- ----------------------------
DROP TABLE IF EXISTS `Paths`;
CREATE TABLE `Paths` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `value` varchar(300) DEFAULT NULL,
  `count` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2357 DEFAULT CHARSET=utf8;

SET FOREIGN_KEY_CHECKS = 1;

**Comment by ThestaRY7** [comment]
不行，感觉是插件获取不到数据，然后保存不到数据库里。

**Comment by gh0stkey** [comment]
麻烦师傅加下我微信：EVILCHEN_，明天白天给你看下。
